# Use the latest 2.1 version of CircleCI pipeline process engine
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build_push_image_karsajobs.sh

# Orchestrate jobs using workflows
workflows:
  lint-test-and-build-karsajobs:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
